# Generated by Django 3.0.4 on 2020-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminEmailId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('adminPassword', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admin_308',
            },
        ),
    ]
