# Generated by Django 3.0.4 on 2020-06-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('showId', models.AutoField(primary_key=True, serialize=False)),
                ('theater', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=20)),
                ('showDate', models.CharField(max_length=50)),
                ('showTime', models.CharField(max_length=50)),
                ('showPrice', models.FloatField(max_length=50)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movieapp.Movie')),
            ],
            options={
                'db_table': 'shows_308',
            },
        ),
    ]
