# Generated by Django 3.0.4 on 2020-08-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0005_shows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='Movie',
            new_name='movie',
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookedSeats', models.CharField(max_length=101)),
                ('totalPrice', models.FloatField(max_length=50)),
                ('bookingDate', models.CharField(max_length=50)),
                ('bookingStatus', models.CharField(default='Processing', max_length=50)),
                ('custEmail', models.CharField(default='Annoymus', max_length=70)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movieapp.Shows')),
            ],
            options={
                'db_table': 'booking_308',
            },
        ),
    ]
