# Generated by Django 3.0.4 on 2020-08-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0006_auto_20200829_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='show',
            new_name='bookedshow',
        ),
    ]
